
server:
  port: 8090

spring:
  datasource:
    username: system
    password: root
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: channanagoudagouda51@gmail.com
    password: wafwrzwxlytpgrty
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true